#!/bin/sh
 
# Coloring the output
healthy='#74cc28'
hot='#cc2828'
blight='#8adae6'
bdark='#14acc2'
batt_healthy='#8cc350'
batt_full='#98ef3b'
batt_low='#ff1919'
batt_discharge='#f7f78f'

# Variables
cpu_healthy=60
gpu_healthy=60
s='|'

# Get device specific values
if [[ -f ~/.config/i3/env ]]
then
    source ~/.config/i3/env
fi
# Set unset variables to default
[[ -z $CPU_COMMAND ]] && CPU_COMMAND='sensors | grep "Physical id 0:" | cut -c18-19'
[[ -z $GPU_COMMAND ]] && GPU_COMMAND='nvidia-smi -q -d TEMPERATURE | awk "/GPU Current Temp/ {print $5}"'
[[ -z $CAPACITY_COMMAND ]] && CAPACITY_COMMAND='cat /sys/class/power_supply/BAT1/capacity'
[[ -z $STATUS_COMMAND ]] && STATUS_COMMAND='cat /sys/class/power_supply/BAT1/status'
 
while :
do
    # Get values
    cpu=$(eval $CPU_COMMAND)
    gpu=$(eval $CPU_COMMAND)
    fday=$(date '+%A')
    fdate=$(date '+%d.%m.%Y')
    ftime=$(date '+%l:%M')
    capacity=$(eval $CAPACITY_COMMAND)
    status=$(eval $STATUS_COMMAND)
    
    if (($cpu >= $cpu_healthy));
    then
        cpus="CPU <span color=\"$hot\">$cpu</span>"
    else
        cpus="CPU <span color=\"$healthy\">$cpu</span>"
    fi

    if (($gpu >= $gpu_healthy));
    then
        gpus="GPU <span color=\"$hot\">$gpu</span>"
    else
        gpus="GPU <span color=\"$healthy\">$gpu</span>"
    fi

    if [[ $capacity != "disabled" ]]
    then
        if (($capacity >= 95));
        then
            battery="<span color=\"$batt_full\"></span>"
        elif (($capacity >= 75));
        then
            if [[ "$status" = "Discharging" ]]
            then
                battery="<span color=\"$batt_discharge\"></span>"
            else
                battery="<span color=\"$batt_healthy\"></span>"
            fi
        elif (($capacity >= 50));
        then
            if [[ "$status" = "Discharging" ]]
            then
                battery="<span color=\"$batt_discharge\"></span>"
            else
                battery="<span color=\"$batt_healthy\"></span>"
            fi
        elif (($capacity >= 25));
        then
            if [[ "$status" = "Discharging" ]]
            then
                battery="<span color=\"$batt_discharge\"></span>"
            else
                battery="<span color=\"$batt_healthy\"></span>"
            fi
        else
            if [[ "$status" = "Discharging" ]]
            then
                battery="<span color=\"$batt_low\"></span>"
            else
                battery="<span color=\"$batt_healthy\"></span>"
            fi
        fi
    fi
    
    dates="<span color=\"$blight\">$fdate</span>"
    times="<span color=\"$bdark\">$ftime</span>"

    # Output the result
    if [[ $capacity != "disabled" ]]
    then
        echo " $fday $dates $s   $cpus $gpus $s $battery  $s $times "
    else
        echo " $fday $dates $s   $cpus $gpus $s $times "
    fi
    sleep 5
done
