#!/bin/sh
 
# Coloring the output
healthy='#64DD17'
hot='#DD2C00'
color='#fff'
accent='#00E5FF'

# Variables
cpu_healthy=60
gpu_healthy=60

# Get device specific values
if [[ -f ~/.config/i3/env ]]
then
    source ~/.config/i3/env
fi
# Set unset variables to default
[[ -z $CPU_COMMAND ]] && CPU_COMMAND='sensors | grep "Physical id 0:" | cut -c18-19'
[[ -z $GPU_COMMAND ]] && GPU_COMMAND='nvidia-smi -q -d TEMPERATURE | awk "/GPU Current Temp/ {print $5}" | cut -c39-40'
 
while :
do
    # Get values
    cpu=$(eval $CPU_COMMAND)
    gpu=$(eval $GPU_COMMAND)
    fday=$(date '+%A')
    fdate=$(date '+%d.%m.%Y')
    ftime=$(date '+%l:%M')
    
    if (($cpu >= $cpu_healthy));
    then
        cpus="CPU <span color=\"$hot\">$cpu</span>"
    else
        cpus="CPU <span color=\"$healthy\">$cpu</span>"
    fi

    if (($gpu >= $gpu_healthy));
    then
        gpus="GPU <span color=\"$hot\">$gpu</span>"
    else
        gpus="GPU <span color=\"$healthy\">$gpu</span>"
    fi

    _date="<span color=\"$accent\">$fdate</span>"
    _time="<span color=\"$accent\">$ftime</span>"

    echo "<span color=\"$color\">  $fday $_date   $cpus $gpus   $_time</span>"
    sleep 5
done
